### ISSUE TITLE
Reporter Output After Task Finishes

### ISSUE THREAD

**Issue by shellscape** [cedx/gulp-david#12]
Running into an odd situation here with both the default reporter and my own reporter, whereby the gulp task completes before the output for the reporter is shown. Not sure if you've got a race condition / async issue or the code is telling the reporter to log too late. The order of output is the same with both the default and my own custom:

```bash
[17:36:30] Starting 'dependencies'...
[17:36:30] Finished 'dependencies' after 9.23 ms

 /.../ui-tracking/src/tracking/cart/package.json 

  dependencies                     package.json  stable  latest
  @gilt-tech/tracking_api.gumshoe  0.2.x         0.3.0   0.3.0
```

And for reference, here's my reporter: https://gist.github.com/shellscape/637c4192f1a14cd31e9aa854e92907ca

*Update*

Yeah looks like you've got an async problem with the subscription: https://github.com/cedx/gulp-david/blob/master/src/checker.js#L130

To avoid this, the plugin should wait for david to resolve. Another of our projects (which uses david directly) yields to a generator function within a call to `co`. Not saying that's the route to go, but since you're already making use of babel, could implement an `async` / `await` pattern here pretty easily.

**Comment by cedx** [comment]
I haven't met this before... Thanks for reporting this issue: I will try to investigate this week-end.

**Comment by shellscape** [comment]
No worries. I wrote a reporter for gulp-david to go along with the other 'stylish' reporters we're using (eslint-stylish, etc) for other parts of our tooling process, which accepts a `done` parameter in the constructor. It was a pretty simple/quick patch to get gulp waiting until the reporter completed reporting: https://github.com/shellscape/gulp-david-stylish

**Comment by cedx** [comment]
Still unable to reproduce the issue: the [Observable](https://github.com/cedx/gulp-david/blob/master/src/checker.js#L98) is resolved as expected. I need more details like your Node.js version, your Gulp.js version, the Gulp-David plugin version, and a sample gulpfile.js. It would be very useful for my investigations.

It's not a reporter issue, but I've tried with [your implementation](https://github.com/shellscape/gulp-david-stylish/blob/master/index.js), but everytime the plugin also ends as expected.

With up-to-date dependencies:

```
$ gulp check
[18:51:19] Using gulpfile C:\repo\gulp-david\gulpfile.js
[18:51:19] Starting 'check'...
[..................] - :
 C:\repo\gulp-david\package.json


  All dependencies up to date.


[18:51:26] Finished 'check' after 1.05 s
```

With outdated dependencies:

```
$ gulp check
[18:53:11] Using gulpfile C:\repo\gulp-david\gulpfile.js
[18:53:11] Starting 'check'...
[..................] / :
 C:\repo\gulp-david\package.json

  devDependencies  package.json  stable  latest
  vinyl            ^1.0.1        2.0.1   2.0.1
  gulp-eslint      ^2.0.1        3.0.1   3.0.1
  isparta          ^3.0.0        4.0.0   4.0.0

[18:53:12] Finished 'check' after 1 s
```

Using the `verbose` mode:

```
$ gulp check
[19:01:37] Using gulpfile C:\repo\gulp-david\gulpfile.js
[19:01:37] Starting 'check'...
[..................] / :
 C:\repo\gulp-david\package.json

  dependencies  package.json  stable  latest
  david         ^9.0.0        9.0.0   9.0.0
  chalk         ^1.1.3        1.1.3   1.1.3
  rxjs          ^5.0.2        5.0.2   5.0.2
  devDependencies      package.json  stable   latest
  gulp                 ^3.9.1        3.9.1    3.9.1
  gulp-load-plugins    ^1.4.0        1.4.0    1.4.0
  esdoc                ^0.4.8        0.4.8    1.0.0
  babel-register       ^6.18.0       6.18.0   6.18.0
  isparta              ^4.0.0        4.0.0    4.0.0
  coveralls            ^2.11.15      2.11.15  2.11.15
  gulp-babel           ^6.1.2        6.1.2    6.1.2
  del                  ^2.2.2        2.2.2    2.2.2
  babel-preset-latest  ^6.16.0       6.16.0   6.16.0
  gulp-istanbul        ^1.1.1        1.1.1    1.1.1
  gulp-eslint          ^3.0.1        3.0.1    3.0.1
  vinyl                ^2.0.1        2.0.1    2.0.1
  gulp-mocha           ^3.0.1        3.0.1    3.0.1
  gulp-zip             ^3.2.0        3.2.0    3.2.0

[19:01:38] Finished 'check' after 829 ms
```

**Comment by shellscape** [comment]
@cedx many thanks for looking into it so thoroughly. I'll spend some time after the holidays and isolate the issue on my end. It may turn out to be an edge case.

**Comment by shellscape** [comment]
turns out I neglected to add a `return` to the gulp task I was using it in. I'd like to apologize for the massive waste of time debugging I caused. rookie mistake that doesn't happen too often anymore, but I still feel like an ass.

**Comment by cedx** [comment]
No problem :)
